# Generated by Django 4.0.3 on 2022-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
