# Generated by Django 4.0.3 on 2022-04-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='published_at',
        ),
    ]
