# Generated by Django 4.0.3 on 2022-04-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_answer_likers_alter_comment_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='to_user',
        ),
    ]
