# Generated by Django 4.0.4 on 2022-04-19 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_answer_comment_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.comment'),
        ),
    ]
