# Generated by Django 4.0.4 on 2022-04-22 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_recentsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearch',
            name='search_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 16, 16, 5, 307190)),
        ),
    ]
