# Generated by Django 4.0.4 on 2022-04-27 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_rename_image_post_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='search_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 17, 19, 29, 916927)),
        ),
    ]
