# Generated by Django 4.0.4 on 2022-04-27 17:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_recentsearch_search_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='search_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 17, 22, 45, 720798)),
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=datetime.datetime.now)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post+', to='backend.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
