# Generated by Django 4.0.4 on 2022-04-30 13:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_recentsearch_search_at_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='search_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 13, 26, 25, 123945)),
        ),
        migrations.RemoveField(
            model_name='saved',
            name='collection',
        ),
        migrations.AddField(
            model_name='saved',
            name='collection',
            field=models.ManyToManyField(related_name='collection+', to='backend.collection'),
        ),
        migrations.AlterField(
            model_name='saved',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post+', to='backend.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saved',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
