# Generated by Django 4.0.3 on 2022-05-07 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_recentsearch_search_at_remove_saved_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='search_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 17, 25, 12, 450515)),
        ),
        migrations.AlterField(
            model_name='saved',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, related_name='collection+', to='backend.collection'),
        ),
    ]
