# Generated by Django 4.0.4 on 2022-05-27 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_recentsearch_search_at_alter_saved_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='search_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 12, 9, 911920)),
        ),
    ]
