# Generated by Django 4.0.4 on 2022-05-27 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_recentsearch_search_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='search_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 13, 48, 521117)),
        ),
    ]
