# Generated by Django 4.0.4 on 2022-05-27 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_recentsearch_search_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='folowers',
            new_name='followers',
        ),
        migrations.AlterField(
            model_name='recentsearch',
            name='search_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 16, 43, 281891)),
        ),
        migrations.AlterField(
            model_name='saved',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collection+', to='backend.collection'),
        ),
    ]
